export const languageMap = new Map([
  ['en', 'English'],
  ['eng', 'English'],
  ['ja', 'Japanese'],
  ['jap', 'Japanese'],
  ['fr', 'French'],
  ['fra', 'French'],
  ['es', 'Spanish'],
  ['spa', 'Spanish'],
  ['de', 'German'],
  ['deu', 'German'],
  ['zh', 'Chinese'],
  ['zho', 'Chinese'],
  ['ru', 'Russian'],
  ['rus', 'Russian'],
  ['ar', 'Arabic'],
  ['ara', 'Arabic'],
  ['pt', 'Portuguese'],
  ['por', 'Portuguese'],
  ['it', 'Italian'],
  ['ita', 'Italian'],
  ['ko', 'Korean'],
  ['kor', 'Korean'],
  ['tr', 'Turkish'],
  ['tur', 'Turkish'],
  ['nl', 'Dutch'],
  ['nld', 'Dutch'],
  ['pl', 'Polish'],
  ['pol', 'Polish'],
  ['sv', 'Swedish'],
  ['swe', 'Swedish'],
  ['da', 'Danish'],
  ['dan', 'Danish'],
  ['fi', 'Finnish'],
  ['fin', 'Finnish'],
  ['no', 'Norwegian'],
  ['nor', 'Norwegian'],
  ['he', 'Hebrew'],
  ['heb', 'Hebrew'],
  ['hi', 'Hindi'],
  ['hin', 'Hindi'],
  ['id', 'Indonesian'],
  ['ind', 'Indonesian'],
  ['uk', 'Ukrainian'],
  ['ukr', 'Ukrainian'],
  ['el', 'Greek'],
  ['ell', 'Greek'],
  ['cs', 'Czech'],
  ['ces', 'Czech'],
  ['hu', 'Hungarian'],
  ['hun', 'Hungarian'],
  ['ro', 'Romanian'],
  ['ron', 'Romanian'],
  ['bg', 'Bulgarian'],
  ['bul', 'Bulgarian'],
  ['th', 'Thai'],
  ['tha', 'Thai'],
  ['vi', 'Vietnamese'],
  ['vie', 'Vietnamese'],
  ['af', 'Afrikaans'],
  ['hye', 'Armenian'],
  ['az', 'Azerbaijani'],
  ['aze', 'Azerbaijani'],
  ['be', 'Belarusian'],
  ['bel', 'Belarusian'],
  ['bs', 'Bosnian'],
  ['bos', 'Bosnian'],
  ['ca', 'Catalan'],
  ['cat', 'Catalan'],
  ['hr', 'Croatian'],
  ['hrv', 'Croatian'],
  ['et', 'Estonian'],
  ['est', 'Estonian'],
  ['gl', 'Galician'],
  ['glg', 'Galician'],
  ['is', 'Icelandic'],
  ['isl', 'Icelandic'],
  ['kn', 'Kannada'],
  ['kan', 'Kannada'],
  ['kk', 'Kazakh'],
  ['kaz', 'Kazakh'],
  ['lv', 'Latvian'],
  ['lav', 'Latvian'],
  ['lt', 'Lithuanian'],
  ['lit', 'Lithuanian'],
  ['mk', 'Macedonian'],
  ['mkd', 'Macedonian'],
  ['ms', 'Malay'],
  ['msa', 'Malay'],
  ['mi', 'Maori'],
  ['mri', 'Maori'],
  ['mr', 'Marathi'],
  ['mar', 'Marathi'],
  ['ne', 'Nepali'],
  ['nep', 'Nepali'],
  ['fa', 'Persian'],
  ['fas', 'Persian'],
  ['sr', 'Serbian'],
  ['srp', 'Serbian'],
  ['sk', 'Slovak'],
  ['slk', 'Slovak'],
  ['sl', 'Slovenian'],
  ['slv', 'Slovenian'],
  ['sw', 'Swahili'],
  ['swa', 'Swahili'],
  ['tl', 'Tagalog'],
  ['tgl', 'Tagalog'],
  ['ta', 'Tamil'],
  ['tam', 'Tamil'],
  ['ur', 'Urdu'],
  ['urd', 'Urdu'],
  ['cy', 'Welsh'],
  ['cym', 'Welsh'],
  ['eu', 'Basque'],
  ['eus', 'Basque'],
  ['tpi', 'Tok Pisin'],
  ['mul', 'Multilingual'],
  ['roa', 'Romance languages'],
  ['ROMANCE', 'Romance languages'],
  ['zlw', 'West Slavic languages'],
  ['sh', 'Serbo-Croatian'],
  ['hbs', 'Serbo-Croatian'],
  ['bn', 'Bengali'],
  ['ben', 'Bengali'],
  ['zle', 'East Slavic languages'],
  ['ml', 'Malayalam'],
  ['sla', 'Slavic languages'],
  ['sq', 'Albanian'],
  ['eo', 'Esperanto'],
  ['gmq', 'North Germanic languages'],
  ['yo', 'Yoruba'],
  ['mt', 'Maltese'],
  ['dra', 'Dravidian languages'],
  ['ceb', 'Cebuano'],
  ['ha', 'Hausa'],
  ['gmw', 'West Germanic languages'],
  ['ces_slk', 'Czech & Slovak'],
  ['ks', 'Kashmiri'],
  ['ZH', 'Chinese'],
  ['xh', 'Xhosa'],
  ['trk', 'Turkic languages'],
  ['hy', 'Armenian'],
  ['mg', 'Malagasy'],
  ['pa', 'Punjabi'],
  ['ig', 'Igbo'],
  ['bat', 'Baltic languages'],
  ['grk', 'Greek languages'],
  ['sm', 'Samoan'],
  ['sn', 'Shona'],
  ['zls', 'South Slavic languages'],
  ['itc', 'Italic languages'],
  ['ny', 'Nyanja'],
  ['guw', 'Gun'],
  ['iir', 'Indo-Iranian languages'],
  ['zhx', 'Chinese languages'],
  ['ti', 'Tigrinya'],
  ['en_el_es_fi', 'English, Greek, Spanish, Finnish'],
  ['swc', 'Congo Swahili'],
  ['pap', 'Papiamento'],
  ['ht', 'Haitian'],
  ['urj', 'Uralic languages'],
  ['aav', 'Austro-Asiatic languages'],
  ['fra_ita_por_spa', 'French, Italian, Portuguese, Spanish'],
  ['gem', 'Germanic languages'],
  ['iso', 'Isoko'],
  ['ln', 'Lingala'],
  ['rnd', 'Rundi'],
  ['to', 'Tongan'],
  ['lua', 'Luba-Lulua'],
  ['wal', 'Wolaytta'],
  ['hil', 'Hiligaynon'],
  ['tiv', 'Tiv'],
  ['CELTIC', 'Celtic languages'],
  ['cel', 'Celtic languages'],
  ['NORTH_EU', 'North European languages'],
  ['NORWAY', 'Norwegian'],
  ['SAMI', 'Sami languages'],
  ['SCANDINAVIA', 'Scandinavian languages'],
  ['aed', 'Argentine Sign Language'],
  ['afa', 'Afro-Asiatic languages'],
  ['alv', 'Atlantic-Congo languages'],
  ['am', 'Amharic'],
  ['art', 'Artificial languages'],
  ['ase', 'American Sign Language'],
  ['bcl', 'Central Bikol'],
  ['bem', 'Bemba'],
  ['ber', 'Berber languages'],
  ['bi', 'Bislama'],
  ['bnt', 'Bantu languages'],
  ['bzs', 'Brazilian Sign Language'],
  ['caenes', 'Catalan, English, Spanish'],
  ['cat_oci_spa', 'Catalan, Occitan, Spanish'],
  ['cau', 'Caucasian languages'],
  ['ccs', 'South Caucasian languages'],
  ['chk', 'Chuukese'],
  ['cpf', 'French-based creoles'],
  ['cpp', 'Portuguese-based creoles'],
  ['crs', 'Seselwa Creole French'],
  ['csg', 'Chilean Sign Language'],
  ['csn', 'Colombian Sign Language'],
  ['cus', 'Cushitic languages'],
  ['ee', 'Ewe'],
  ['efi', 'Efik'],
  ['euq', 'Basque'],
  ['fi_nb_no_nn_ru_sv_en', 'Finnish, Norwegian, Russian, Swedish, English'],
  ['fiu', 'Finno-Ugric languages'],
  ['fj', 'Fijian'],
  ['fse', 'Finnish Sign Language'],
  ['ga', 'Irish'],
  ['gaa', 'Ga'],
  ['gil', 'Gilbertese'],
  ['gv', 'Manx'],
  ['ho', 'Hiri Motu'],
  ['ilo', 'Iloko'],
  ['inc', 'Indo-Aryan languages'],
  ['ine', 'Indo-European languages'],
  ['ka', 'Georgian'],
  ['kab', 'Kabyle'],
  ['kg', 'Kongo'],
  ['kj', 'Kuanyama'],
  ['kl', 'Kalaallisut'],
  ['kqn', 'Kaonde'],
  ['kwn', 'Kwangali'],
  ['kwy', 'San Salvador Kongo'],
  ['lg', 'Ganda'],
  ['loz', 'Lozi'],
  ['lu', 'Luba-Katanga'],
  ['lue', 'Luvale'],
  ['lun', 'Lunda'],
  ['luo', 'Luo'],
  ['lus', 'Lushai'],
  ['map', 'Austronesian languages'],
  ['mfe', 'Mauritian Creole'],
  ['mfs', 'Mexican Sign Language'],
  ['mh', 'Marshallese'],
  ['mkh', 'Mon-Khmer languages'],
  ['mos', 'Mossi'],
  ['ng', 'Ndonga'],
  ['nic', 'Niger-Kordofanian languages'],
  ['niu', 'Niuean'],
  ['nso', 'Northern Sotho'],
  ['nyk', 'Nyankole'],
  ['om', 'Oromo'],
  ['pag', 'Pangasinan'],
  ['phi', 'Philippine languages'],
  ['pis', 'Pijin'],
  ['pon', 'Pohnpeian'],
  ['poz', 'Malayo-Polynesian languages'],
  ['pqe', 'Eastern Malayo-Polynesian languages'],
  ['pqw', 'Western Malayo-Polynesian languages'],
  ['prl', 'Peruvian Sign Language'],
  ['rn', 'Rundi'],
  ['run', 'Rundi'],
  ['rw', 'Kinyarwanda'],
  ['sal', 'Salishan languages'],
  ['sem', 'Semitic languages'],
  ['sg', 'Sango'],
  ['sit', 'Sino-Tibetan languages'],
  ['srn', 'Sranan Tongo'],
  ['ss', 'Swati'],
  ['ssp', 'Spanish Sign Language'],
  ['st', 'Southern Sotho'],
  ['taw', 'Tai languages'],
  ['tdt', 'Timor-Alor-Pantar languages'],
  ['tll', 'Tetum'],
  ['tn', 'Tswana'],
  ['toi', 'Tonga'],
  ['ts', 'Tsonga'],
  ['tum', 'Tumbuka'],
  ['tut', 'Altaic languages'],
  ['tvl', 'Tuvaluan'],
  ['tw', 'Twi'],
  ['ty', 'Tahitian'],
  ['tzo', 'Tzotzil'],
  ['umb', 'Umbundu'],
  ['ve', 'Venda'],
  ['vsl', 'Venezuelan Sign Language'],
  ['wa', 'Walloon'],
  ['war', 'Waray'],
  ['wls', 'Wallisian'],
  ['yap', 'Yapese'],
  ['yua', 'Yucatec Maya'],
  ['zai', 'Isthmus Zapotec'],
  ['zne', 'Zande languages']
]);
